// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flhrbrnuwkpcdsnplibo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaHJicm51d2twY2RzbnBsaWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MjQ3MzYsImV4cCI6MjA5MDUwMDczNn0.QqgPA0qnK1mdZnHhVeakBmceyz4sZ2jec18zjRe3v1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});